# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e04954f1b30ab1a0a53fe204abba22d3b21721024be967b3280ccfa5c60bd75c6dfc9ff09940204c991b002ede636f77a0c5152a29a3fdfd832f280b423333

test:
  secret_key_base: e890930a8251b9e6a8fab1b06454ab7a561316ebdce9858d61544313569b47178cc770f5363c2cc6dee2dd1720b37e5615842d326604279b48712320a4cfb19e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
